name: acquisition

services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    restart: unless-stopped
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Los_Angeles
      - NZBGET_USER=
      - NZBGET_PASS=
    ports:
      - "6789:6789"
    volumes:
      - nzbget_config:/config
      - "/Volumes/Thermal Silencer/Downloads:/downloads"
      - "/Volumes/Thermal Silencer:/intermediate"

volumes:
  nzbget_config: